apiVersion: v1
kind: Service
metadata:
  name: contact-server
  labels:
    app: qvbilam-grpc
spec:
  selector:
    app: contact-server
  ports:
    - name: grpc-contact-server
      protocol: TCP
      port: 9805
      targetPort: 9501
  type: NodePort